In [3]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import re
from selenium.webdriver.common.keys import Keys
import pandas as pd
import numpy as np
import random as rd

Here I created new data frame and scraped from Goldin website which known well for its auctions of trading cards.

In [4]:
#df = pd.DataFrame()

In [6]:
#Single cards - football 
link = "https://goldin.co/buy/?show_only=Sold%20Items&page=1&number_of_lots=96&Item_Type=Single%2520Cards&Sub_Category=Football"
driver =webdriver.Chrome()
driver.get(link)
driver.implicitly_wait(10)
cards = driver.find_elements(By.CSS_SELECTOR,".css-175oi2r.r-1udh08x.r-y46g1k")

In [151]:
count1 = 0
count2 = 1

for i in range(45,74):
    for card in cards:
        driver.implicitly_wait(30)
        title = card.find_element(By.CSS_SELECTOR,".css-1rynq56.r-8akbws.r-krxsd3.r-dnmrzs.r-1udh08x.r-1udbk01").text
        bids = card.find_element(By.CSS_SELECTOR,".css-175oi2r.r-1d09ksm.r-18u37iz").find_elements(By.CSS_SELECTOR,".css-1rynq56")[1].text
        link = card.find_element(By.CSS_SELECTOR, ".css-175oi2r.r-1awozwy.r-1jj8364.r-13qz1uu").get_attribute("href")
        date = card.find_element(By.CSS_SELECTOR,".css-175oi2r.r-1wtj0ep.r-kzbkwu.r-m2pi6t.r-1hvjb8t.r-tskmnb").text
        price = card.find_element(By.CSS_SELECTOR,".css-175oi2r.r-1d09ksm.r-18u37iz").find_elements(By.CSS_SELECTOR,".css-1rynq56")[0].text
        err_date = 0
        err_bids = 0
        try:
            bids = re.findall("([0-9]*) bids", bids)[0]
        except:
            print("Try again in bids...")
            bids = card.find_element(By.CSS_SELECTOR,".css-175oi2r.r-1d09ksm.r-18u37iz").find_elements(By.CSS_SELECTOR,".css-1rynq56")[1].text
            try:
                bids = re.findall("([0-9]*) bids", bids)[0]
            except:
                err_bids = 1
                bids = str(count1) + "," +str(count2) 

        fixed_date = re.findall("(Mon|Tue|Wed|Thu|Fri|Sat|Sun), (.*), (.*) (AM|PM)", date)
        try:
            weekday = fixed_date[0][0]
            fulldate = fixed_date[0][1]
            hour = fixed_date[0][2]
            ampm = fixed_date[0][3]
        except:
            print("try again in date...")
            try:
                date = card.find_element(By.CSS_SELECTOR,".css-175oi2r.r-1wtj0ep.r-kzbkwu.r-m2pi6t.r-1hvjb8t.r-tskmnb").text
                fixed_date = re.findall("(Mon|Tue|Wed|Thu|Fri|Sat|Sun), (.*), (.*) (AM|PM)", date)
                weekday = fixed_date[0][0]
                fulldate = fixed_date[0][1]
                hour = fixed_date[0][2]
                ampm = fixed_date[0][3]
            except:
                err_date = 1
                weekday = str(count1) + ',' + str(count2)
                fulldate = str(count1) + ',' + str(count2)
                hour = str(count1) + ',' + str(count2)
                ampm = str(count1) + ',' + str(count2)

        '''
        print(title)
        print(bids)
        print(link)
        print(price)
        print(weekday, ", ", fulldate, ", ", hour," ", ampm)
        print("======")
        '''
        
        
        row = pd.Series({"title":title,"bids":bids,"err_bids":err_bids,"link": link, "price": price,"weekday":weekday, "date":fulldate,"err_date":err_date, "hour":hour, "ampm": ampm})
        df = pd.concat([df, row.to_frame().T], ignore_index=True)
        count1 = count1 +1
    link = "https://goldin.co/buy/?show_only=Sold%20Items&page=" + str(i) + "&number_of_lots=96&Item_Type=Single%2520Cards&Sub_Category=Football"
    driver.get(link)
    driver.implicitly_wait(30)
    cards = driver.find_elements(By.CSS_SELECTOR,".css-175oi2r.r-1udh08x.r-y46g1k")
    count2 = count2 + 1
    print("count1: " , count1, " count2: " ,  i , " in 73")
print("END")

Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  88  count2:  45  in 73
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
count1:  184  count2:  46  in 73
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...

Try again in bids...
try again in date...
count1:  280  count2:  47  in 73
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
count1:  376  count2:  48  in 73
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
count1:  472  count2:  49  in 73

Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
count1:  568  count2:  50  in 73
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
count1:  664  count2:  51  in 73
Try again in bids...
try again in date...
Try again in bids...
try again in date...

Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
count1:  760  count2:  52  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  856  count2:  53  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  952  count2:  54  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  1048  count2:  55  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  1144  count2:  56  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  1240  count2:  57  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  1336  count2:  58  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  1432  count2:  59  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  1528  count2:  60  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  1624  count2:  61  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  1720  count2:  62  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  1816  count2:  63  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  1912  count2:  64  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  2008  count2:  65  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  2104  count2:  66  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...

Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  2200  count2:  67  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  2296  count2:  68  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  2392  count2:  69  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  2488  count2:  70  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  2584  count2:  71  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  2680  count2:  72  in 73
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  2776  count2:  73  in 73
END

In [152]:
df

,title,bids,err_bids,link,price,weekday,date,err_date,hour,ampm
0,2000 Playoff Contenders Championship Ticket Au...,10,0,https://goldin.co/item/2000-playoff-contender-...,"$114,000",Thu,3/30/23,0,4:30,AM
1,1976 Topps #148 Walter Payton Rookie Card – PS...,23,0,https://goldin.co/item/1976-topps-148-walter-p...,"$61,200",Thu,3/16/23,0,3:30,AM
2,2021 Panini National Treasures Rookie Patch Au...,32,0,https://goldin.co/item/2021-panini-national-tr...,"$264,000",Thu,3/30/23,0,5:44,AM
3,2000 Playoff Contenders Championship Ticket Au...,23,0,https://goldin.co/item/2000-playoff-contenders...,"$570,000",Thu,3/02/23,0,5:03,AM
4,"1933 Sport Kings #6 Jim Thorpe, Football - PSA...",18,0,https://goldin.co/item/1933-sport-kings-footba...,"$43,200",Thu,5/18/23,0,5:49,AM
...,...,...,...,...,...,...,...,...,...,...
7067,1972 Topps #150 Terry Bradshaw - PSA EX-MT 6,11,0,https://goldin.co/item/1972-topps-150-terry-br...,$38,Fri,5/19/23,0,4:15,AM
7068,1972 Topps #150 Terry Bradshaw – PSA VG-EX 4,5,0,https://goldin.co/item/1972-topps-150-terry-br...,$16,Fri,5/19/23,0,4:15,AM
7069,1972 Topps #100 Joe Namath - PSA EX 5,6,0,https://goldin.co/item/1972-topps-100-joe-nama...,$23,Fri,5/19/23,0,4:15,AM
7070,1972 Topps #100 Joe Namath - PSA EX 5,8,0,https://goldin.co/item/1972-topps-100-joe-nama...,$23,Fri,5/19/23,0,4:15,AM
7071,1972 Topps #160 O.J. Simpson - PSA VG-EX 4,3,0,https://goldin.co/item/1972-topps-160-o-j-simp...,$11,Fri,5/05/23,0,4:15,AM

In [169]:
df = pd.read_csv("Football.csv")
df = df.drop(df.columns[0],axis="columns")
df

,title,bids,err_bids,link,price,weekday,date,err_date,hour,ampm
0,2000 Playoff Contenders Championship Ticket Au...,10,0,https://goldin.co/item/2000-playoff-contender-...,"$114,000",Thu,3/30/23,0,4:30,AM
1,1976 Topps #148 Walter Payton Rookie Card – PS...,23,0,https://goldin.co/item/1976-topps-148-walter-p...,"$61,200",Thu,3/16/23,0,3:30,AM
2,2021 Panini National Treasures Rookie Patch Au...,32,0,https://goldin.co/item/2021-panini-national-tr...,"$264,000",Thu,3/30/23,0,5:44,AM
3,2000 Playoff Contenders Championship Ticket Au...,23,0,https://goldin.co/item/2000-playoff-contenders...,"$570,000",Thu,3/02/23,0,5:03,AM
4,"1933 Sport Kings #6 Jim Thorpe, Football - PSA...",18,0,https://goldin.co/item/1933-sport-kings-footba...,"$43,200",Thu,5/18/23,0,5:49,AM
...,...,...,...,...,...,...,...,...,...,...
5559,1983 Topps #36 Walter Payton - PSA EX-MT 6,2,0,https://goldin.co/item/1983-topps-36-walter-pa...,$11,Fri,5/12/23,0,4:15,AM
5560,1972 Topps #200 Roger Staubach – PSA EX-MT 6,16,0,https://goldin.co/item/1972-topps-200-roger-st...,$282,Fri,5/19/23,0,4:15,AM
5561,1972 Topps #150 Terry Bradshaw - PSA EX-MT 6,11,0,https://goldin.co/item/1972-topps-150-terry-br...,$38,Fri,5/19/23,0,4:15,AM
5562,1972 Topps #150 Terry Bradshaw – PSA VG-EX 4,5,0,https://goldin.co/item/1972-topps-150-terry-br...,$16,Fri,5/19/23,0,4:15,AM
5563,1972 Topps #160 O.J. Simpson - PSA VG-EX 4,3,0,https://goldin.co/item/1972-topps-160-o-j-simp...,$11,Fri,5/05/23,0,4:15,AM

In [160]:
list_err = []
for i in range(0,len(df)):
    if(df.iloc[i, 2]==1 or df.iloc[i,7]==1):
            list_err.append(i)
df = df.drop(index=list_err)

Dropping duplicates because I did scraping again and again until I got enough records

In [170]:
df.drop_duplicates(subset=['title','link'], inplace=True)
df

,title,bids,err_bids,link,price,weekday,date,err_date,hour,ampm
0,2000 Playoff Contenders Championship Ticket Au...,10,0,https://goldin.co/item/2000-playoff-contender-...,"$114,000",Thu,3/30/23,0,4:30,AM
1,1976 Topps #148 Walter Payton Rookie Card – PS...,23,0,https://goldin.co/item/1976-topps-148-walter-p...,"$61,200",Thu,3/16/23,0,3:30,AM
2,2021 Panini National Treasures Rookie Patch Au...,32,0,https://goldin.co/item/2021-panini-national-tr...,"$264,000",Thu,3/30/23,0,5:44,AM
3,2000 Playoff Contenders Championship Ticket Au...,23,0,https://goldin.co/item/2000-playoff-contenders...,"$570,000",Thu,3/02/23,0,5:03,AM
4,"1933 Sport Kings #6 Jim Thorpe, Football - PSA...",18,0,https://goldin.co/item/1933-sport-kings-footba...,"$43,200",Thu,5/18/23,0,5:49,AM
...,...,...,...,...,...,...,...,...,...,...
5559,1983 Topps #36 Walter Payton - PSA EX-MT 6,2,0,https://goldin.co/item/1983-topps-36-walter-pa...,$11,Fri,5/12/23,0,4:15,AM
5560,1972 Topps #200 Roger Staubach – PSA EX-MT 6,16,0,https://goldin.co/item/1972-topps-200-roger-st...,$282,Fri,5/19/23,0,4:15,AM
5561,1972 Topps #150 Terry Bradshaw - PSA EX-MT 6,11,0,https://goldin.co/item/1972-topps-150-terry-br...,$38,Fri,5/19/23,0,4:15,AM
5562,1972 Topps #150 Terry Bradshaw – PSA VG-EX 4,5,0,https://goldin.co/item/1972-topps-150-terry-br...,$16,Fri,5/19/23,0,4:15,AM
5563,1972 Topps #160 O.J. Simpson - PSA VG-EX 4,3,0,https://goldin.co/item/1972-topps-160-o-j-simp...,$11,Fri,5/05/23,0,4:15,AM

In [174]:
df.to_csv("Football.csv")
df

,title,bids,err_bids,link,price,weekday,date,err_date,hour,ampm,Description
0,2000 Playoff Contenders Championship Ticket Au...,10,0,https://goldin.co/item/2000-playoff-contender-...,"$114,000",Thu,3/30/23,0,4:30,AM,
1,1976 Topps #148 Walter Payton Rookie Card – PS...,23,0,https://goldin.co/item/1976-topps-148-walter-p...,"$61,200",Thu,3/16/23,0,3:30,AM,
2,2021 Panini National Treasures Rookie Patch Au...,32,0,https://goldin.co/item/2021-panini-national-tr...,"$264,000",Thu,3/30/23,0,5:44,AM,
3,2000 Playoff Contenders Championship Ticket Au...,23,0,https://goldin.co/item/2000-playoff-contenders...,"$570,000",Thu,3/02/23,0,5:03,AM,
4,"1933 Sport Kings #6 Jim Thorpe, Football - PSA...",18,0,https://goldin.co/item/1933-sport-kings-footba...,"$43,200",Thu,5/18/23,0,5:49,AM,
...,...,...,...,...,...,...,...,...,...,...,...
5559,1983 Topps #36 Walter Payton - PSA EX-MT 6,2,0,https://goldin.co/item/1983-topps-36-walter-pa...,$11,Fri,5/12/23,0,4:15,AM,
5560,1972 Topps #200 Roger Staubach – PSA EX-MT 6,16,0,https://goldin.co/item/1972-topps-200-roger-st...,$282,Fri,5/19/23,0,4:15,AM,
5561,1972 Topps #150 Terry Bradshaw - PSA EX-MT 6,11,0,https://goldin.co/item/1972-topps-150-terry-br...,$38,Fri,5/19/23,0,4:15,AM,
5562,1972 Topps #150 Terry Bradshaw – PSA VG-EX 4,5,0,https://goldin.co/item/1972-topps-150-terry-br...,$16,Fri,5/19/23,0,4:15,AM,
5563,1972 Topps #160 O.J. Simpson - PSA VG-EX 4,3,0,https://goldin.co/item/1972-topps-160-o-j-simp...,$11,Fri,5/05/23,0,4:15,AM,

In [163]:
df.iloc[:,2].value_counts()

0    5907
Name: err_bids, dtype: int64

In [173]:
#df["Description"] = ''
df

,title,bids,err_bids,link,price,weekday,date,err_date,hour,ampm,Description
0,2000 Playoff Contenders Championship Ticket Au...,10,0,https://goldin.co/item/2000-playoff-contender-...,"$114,000",Thu,3/30/23,0,4:30,AM,
1,1976 Topps #148 Walter Payton Rookie Card – PS...,23,0,https://goldin.co/item/1976-topps-148-walter-p...,"$61,200",Thu,3/16/23,0,3:30,AM,
2,2021 Panini National Treasures Rookie Patch Au...,32,0,https://goldin.co/item/2021-panini-national-tr...,"$264,000",Thu,3/30/23,0,5:44,AM,
3,2000 Playoff Contenders Championship Ticket Au...,23,0,https://goldin.co/item/2000-playoff-contenders...,"$570,000",Thu,3/02/23,0,5:03,AM,
4,"1933 Sport Kings #6 Jim Thorpe, Football - PSA...",18,0,https://goldin.co/item/1933-sport-kings-footba...,"$43,200",Thu,5/18/23,0,5:49,AM,
...,...,...,...,...,...,...,...,...,...,...,...
5559,1983 Topps #36 Walter Payton - PSA EX-MT 6,2,0,https://goldin.co/item/1983-topps-36-walter-pa...,$11,Fri,5/12/23,0,4:15,AM,
5560,1972 Topps #200 Roger Staubach – PSA EX-MT 6,16,0,https://goldin.co/item/1972-topps-200-roger-st...,$282,Fri,5/19/23,0,4:15,AM,
5561,1972 Topps #150 Terry Bradshaw - PSA EX-MT 6,11,0,https://goldin.co/item/1972-topps-150-terry-br...,$38,Fri,5/19/23,0,4:15,AM,
5562,1972 Topps #150 Terry Bradshaw – PSA VG-EX 4,5,0,https://goldin.co/item/1972-topps-150-terry-br...,$16,Fri,5/19/23,0,4:15,AM,
5563,1972 Topps #160 O.J. Simpson - PSA VG-EX 4,3,0,https://goldin.co/item/1972-topps-160-o-j-simp...,$11,Fri,5/05/23,0,4:15,AM,

In [177]:
#df = pd.read_csv("Football.csv")
#df.drop(df.columns[0], axis=1, inplace=True)
#df.drop(df.columns[0], axis=1, inplace=True)
#df.to_csv("Football.csv")
#df

,title,bids,err_bids,link,price,weekday,date,err_date,hour,ampm,Description
0,2000 Playoff Contenders Championship Ticket Au...,10,0,https://goldin.co/item/2000-playoff-contender-...,"$114,000",Thu,3/30/23,0,4:30,AM,NaN
1,1976 Topps #148 Walter Payton Rookie Card – PS...,23,0,https://goldin.co/item/1976-topps-148-walter-p...,"$61,200",Thu,3/16/23,0,3:30,AM,NaN
2,2021 Panini National Treasures Rookie Patch Au...,32,0,https://goldin.co/item/2021-panini-national-tr...,"$264,000",Thu,3/30/23,0,5:44,AM,NaN
3,2000 Playoff Contenders Championship Ticket Au...,23,0,https://goldin.co/item/2000-playoff-contenders...,"$570,000",Thu,3/02/23,0,5:03,AM,NaN
4,"1933 Sport Kings #6 Jim Thorpe, Football - PSA...",18,0,https://goldin.co/item/1933-sport-kings-footba...,"$43,200",Thu,5/18/23,0,5:49,AM,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5559,1983 Topps #36 Walter Payton - PSA EX-MT 6,2,0,https://goldin.co/item/1983-topps-36-walter-pa...,$11,Fri,5/12/23,0,4:15,AM,NaN
5560,1972 Topps #200 Roger Staubach – PSA EX-MT 6,16,0,https://goldin.co/item/1972-topps-200-roger-st...,$282,Fri,5/19/23,0,4:15,AM,NaN
5561,1972 Topps #150 Terry Bradshaw - PSA EX-MT 6,11,0,https://goldin.co/item/1972-topps-150-terry-br...,$38,Fri,5/19/23,0,4:15,AM,NaN
5562,1972 Topps #150 Terry Bradshaw – PSA VG-EX 4,5,0,https://goldin.co/item/1972-topps-150-terry-br...,$16,Fri,5/19/23,0,4:15,AM,NaN
5563,1972 Topps #160 O.J. Simpson - PSA VG-EX 4,3,0,https://goldin.co/item/1972-topps-160-o-j-simp...,$11,Fri,5/05/23,0,4:15,AM,NaN

<a id='save'>Save into CSV file</a>

In [288]:
start = 0
end = 5564
index =10
df.to_csv('Football.csv')
df.iloc[start:end,:]

,title,bids,err_bids,link,price,weekday,date,err_date,hour,ampm,Description
0,2000 Playoff Contenders Championship Ticket Au...,10,0,https://goldin.co/item/2000-playoff-contender-...,"$114,000",Thu,3/30/23,0,4:30,AM,"Encapsulated and assessed ""Authentic"" by PSA, ..."
1,1976 Topps #148 Walter Payton Rookie Card – PS...,23,0,https://goldin.co/item/1976-topps-148-walter-p...,"$61,200",Thu,3/16/23,0,3:30,AM,Graded GEM MT 10 by PSA (63938572). Hall of Fa...
2,2021 Panini National Treasures Rookie Patch Au...,32,0,https://goldin.co/item/2021-panini-national-tr...,"$264,000",Thu,3/30/23,0,5:44,AM,"Graded NM-MT 8 by BGS, with Autograph Grade 10..."
3,2000 Playoff Contenders Championship Ticket Au...,23,0,https://goldin.co/item/2000-playoff-contenders...,"$570,000",Thu,3/02/23,0,5:03,AM,Graded NM-MT 8 by PSA (19778427). Rookie Card....
4,"1933 Sport Kings #6 Jim Thorpe, Football - PSA...",18,0,https://goldin.co/item/1933-sport-kings-footba...,"$43,200",Thu,5/18/23,0,5:49,AM,Graded NM-MT 8 by PSA (09031682). Hall of Fame...
...,...,...,...,...,...,...,...,...,...,...,...
5559,1983 Topps #36 Walter Payton - PSA EX-MT 6,2,0,https://goldin.co/item/1983-topps-36-walter-pa...,$11,Fri,5/12/23,0,4:15,AM,Walter Payton—the 1977 NFL Most Valuable Playe...
5560,1972 Topps #200 Roger Staubach – PSA EX-MT 6,16,0,https://goldin.co/item/1972-topps-200-roger-st...,$282,Fri,5/19/23,0,4:15,AM,No Data
5561,1972 Topps #150 Terry Bradshaw - PSA EX-MT 6,11,0,https://goldin.co/item/1972-topps-150-terry-br...,$38,Fri,5/19/23,0,4:15,AM,No Data
5562,1972 Topps #150 Terry Bradshaw – PSA VG-EX 4,5,0,https://goldin.co/item/1972-topps-150-terry-br...,$16,Fri,5/19/23,0,4:15,AM,No Data
5563,1972 Topps #160 O.J. Simpson - PSA VG-EX 4,3,0,https://goldin.co/item/1972-topps-160-o-j-simp...,$11,Fri,5/05/23,0,4:15,AM,Authentication-PSA-CLQALI3HFY

In [289]:
long = len(df)
driver =webdriver.Chrome()
for i in range(start,end):
    if(pd.isnull(df.iloc[i,index]) or df.iloc[i,index]=='NaN' or df.iloc[i,index]==""):
        print(i ," in ", long)
        flag = 1
        try:
            link = df.at[i,"link"]
        except:
            print("Error in ", i)
            flag = 0
        if(flag):
            driver.get(link)
            driver.implicitly_wait(8)
        try:
            des = driver.find_element(By.XPATH,"//div[@class='css-175oi2r'][@id = 'html-description']").text
        except:
            des = 'No Data'
        df.iloc[i,index]=des
print("END")

END

For saveing df into CSV file, I need to do again [here](#save)