In [334]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import re
from selenium.webdriver.common.keys import Keys
import pandas as pd
import numpy as np
import random as rd
from matplotlib import pyplot as plt
import seaborn as sns
import time
%matplotlib inline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cluster import KMeans
from matplotlib.colors import ListedColormap

Here I created new data frame and scraped from Goldin website which known well for its auctions of trading cards.

In [3]:
#df = pd.DataFrame()

In [250]:
#Single cards - Baseball 
link = "https://goldin.co/buy/?show_only=Sold%20Items&page=1&number_of_lots=96&Item_Type=Single%2520Cards&Sub_Category=Baseball"
driver =webdriver.Chrome()
driver.get(link)
driver.implicitly_wait(10)
cards = driver.find_elements(By.CSS_SELECTOR,".css-175oi2r.r-1udh08x.r-y46g1k")

In [251]:
count1 = 0
count2 = 1

for i in range(2,105):
    time.sleep(3.5)
    for card in cards:
        driver.implicitly_wait(30)
        title = card.find_element(By.CSS_SELECTOR,".css-1rynq56.r-8akbws.r-krxsd3.r-dnmrzs.r-1udh08x.r-1udbk01").text
        bids = card.find_element(By.CSS_SELECTOR,".css-175oi2r.r-1d09ksm.r-18u37iz").find_elements(By.CSS_SELECTOR,".css-1rynq56")[1].text
        link = card.find_element(By.CSS_SELECTOR, ".css-175oi2r.r-1awozwy.r-1jj8364.r-13qz1uu").get_attribute("href")
        date = card.find_element(By.CSS_SELECTOR,".css-175oi2r.r-1wtj0ep.r-kzbkwu.r-m2pi6t.r-1hvjb8t.r-tskmnb").text
        price = card.find_element(By.CSS_SELECTOR,".css-175oi2r.r-1d09ksm.r-18u37iz").find_elements(By.CSS_SELECTOR,".css-1rynq56")[0].text
        err_date = 0
        err_bids = 0
        try:
            bids = re.findall("([0-9]*) bids", bids)[0]
        except:
            print("Try again in bids...")
            bids = card.find_element(By.CSS_SELECTOR,".css-175oi2r.r-1d09ksm.r-18u37iz").find_elements(By.CSS_SELECTOR,".css-1rynq56")[1].text
            try:
                bids = re.findall("([0-9]*) bids", bids)[0]
            except:
                err_bids = 1
                bids = str(count1) + "," +str(count2) 

        fixed_date = re.findall("(Mon|Tue|Wed|Thu|Fri|Sat|Sun), (.*), (.*) (AM|PM)", date)
        try:
            weekday = fixed_date[0][0]
            fulldate = fixed_date[0][1]
            hour = fixed_date[0][2]
            ampm = fixed_date[0][3]
        except:
            print("try again in date...")
            try:
                date = card.find_element(By.CSS_SELECTOR,".css-175oi2r.r-1wtj0ep.r-kzbkwu.r-m2pi6t.r-1hvjb8t.r-tskmnb").text
                fixed_date = re.findall("(Mon|Tue|Wed|Thu|Fri|Sat|Sun), (.*), (.*) (AM|PM)", date)
                weekday = fixed_date[0][0]
                fulldate = fixed_date[0][1]
                hour = fixed_date[0][2]
                ampm = fixed_date[0][3]
            except:
                err_date = 1
                weekday = str(count1) + ',' + str(count2)
                fulldate = str(count1) + ',' + str(count2)
                hour = str(count1) + ',' + str(count2)
                ampm = str(count1) + ',' + str(count2)

        '''
        print(title)
        print(bids)
        print(link)
        print(price)
        print(weekday, ", ", fulldate, ", ", hour," ", ampm)
        print("======")
        '''
        
        
        row = pd.Series({"title":title,"bids":bids,"err_bids":err_bids,"link": link, "price": price,"weekday":weekday, "date":fulldate,"err_date":err_date, "hour":hour, "ampm": ampm})
        df = pd.concat([df, row.to_frame().T], ignore_index=True)
        count1 = count1 +1
    link = "https://goldin.co/buy/?show_only=Sold%20Items&page=" +  str(i) +"&number_of_lots=96&Item_Type=Single%2520Cards&Sub_Category=Baseball"
    driver.get(link)
    driver.implicitly_wait(30)
    cards = driver.find_elements(By.CSS_SELECTOR,".css-175oi2r.r-1udh08x.r-y46g1k")
    count2 = count2 + 1
    print("count1: " , count1, " count2: " ,  count2 , " in 104")

count1:  96  count2:  2  in 104
count1:  192  count2:  3  in 104
Try again in bids...
Try again in bids...
Try again in bids...
count1:  288  count2:  4  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  384  count2:  5  in 104
Try again in bids...
count1:  480  count2:  6  in 104
Try again in bids...
count1:  576  count2:  7  in 104
Try again in bids...
Try again in bids...
count1:  672  count2:  8  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  768  count2:  9  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  864  count2:  10  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  960  count2:  11  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  1056  count2:  12  in 104
count1:  1152  count2:  13  in 104
count1:  1248  count2:  14  in 104
Try again in bids...
Try again in bids...
Try again in bids...
count1:  1344  count2:  15  in 104
Try again in bids...
Try again in bids...
count1:  1440  count2:  16  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  1536  count2:  17  in 104
Try again in bids...
Try again in bids...
Try again in bids...
count1:  1632  count2:  18  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  1728  count2:  19  in 104
Try again in bids...
count1:  1824  count2:  20  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  1920  count2:  21  in 104
Try again in bids...
Try again in bids...
count1:  2016  count2:  22  in 104
Try again in bids...
count1:  2112  count2:  23  in 104
Try again in bids...
Try again in bids...
Try again in bids...
count1:  2208  count2:  24  in 104
Try again in bids...
Try again in bids...
count1:  2304  count2:  25  in 104
Try again in bids...
Try again in bids...
Try again in bids...
count1:  2400  count2:  26  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  2496  count2:  27  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  2592  count2:  28  in 104
count1:  2688  count2:  29  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  2784  count2:  30  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  2880  count2:  31  in 104
Try again in bids...
Try again in bids...
count1:  2976  count2:  32  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  3072  count2:  33  in 104
Try again in bids...
count1:  3168  count2:  34  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  3264  count2:  35  in 104
count1:  3360  count2:  36  in 104
Try again in bids...
Try again in bids...
Try again in bids...
count1:  3456  count2:  37  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  3552  count2:  38  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  3648  count2:  39  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  3744  count2:  40  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  3840  count2:  41  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  3936  count2:  42  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  4032  count2:  43  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  4128  count2:  44  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  4224  count2:  45  in 104
Try again in bids...
Try again in bids...
count1:  4320  count2:  46  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  4416  count2:  47  in 104
Try again in bids...
Try again in bids...
count1:  4512  count2:  48  in 104
Try again in bids...
Try again in bids...
count1:  4608  count2:  49  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  4704  count2:  50  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  4800  count2:  51  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  4896  count2:  52  in 104
Try again in bids...
Try again in bids...
Try again in bids...
count1:  4992  count2:  53  in 104
Try again in bids...
count1:  5088  count2:  54  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  5184  count2:  55  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  5280  count2:  56  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  5376  count2:  57  in 104
Try again in bids...
Try again in bids...
Try again in bids...
count1:  5472  count2:  58  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  5568  count2:  59  in 104

Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  5664  count2:  60  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  5760  count2:  61  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  5856  count2:  62  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  5952  count2:  63  in 104
Try again in bids...
Try again in bids...
count1:  6048  count2:  64  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  6144  count2:  65  in 104
Try again in bids...
Try again in bids...
count1:  6240  count2:  66  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  6336  count2:  67  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  6432  count2:  68  in 104
Try again in bids...
count1:  6528  count2:  69  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  6624  count2:  70  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  6720  count2:  71  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  6816  count2:  72  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  6912  count2:  73  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  7008  count2:  74  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  7104  count2:  75  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  7200  count2:  76  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  7296  count2:  77  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  7392  count2:  78  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  7488  count2:  79  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  7584  count2:  80  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  7680  count2:  81  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  7776  count2:  82  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  7872  count2:  83  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  7968  count2:  84  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  8064  count2:  85  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  8160  count2:  86  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  8256  count2:  87  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  8352  count2:  88  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  8448  count2:  89  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  8544  count2:  90  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  8640  count2:  91  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  8736  count2:  92  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  8832  count2:  93  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  8928  count2:  94  in 104
Try again in bids...
Try again in bids...
Try again in bids...
count1:  9024  count2:  95  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...

Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  9120  count2:  96  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  9216  count2:  97  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  9312  count2:  98  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  9408  count2:  99  in 104
count1:  9408  count2:  100  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  9504  count2:  101  in 104
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  9600  count2:  102  in 104
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
count1:  9696  count2:  103  in 104
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
try again in date...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
Try again in bids...
count1:  9792  count2:  104  in 104

Dropping duplicates because I did scraping again and again until I got enough records

In [256]:

#df.drop_duplicates(subset='link', inplace=True)
#df.drop_duplicates(subset='title', inplace=True)
#df

,title,bids,err_bids,link,price,weekday,date,err_date,hour,ampm
0,1951 Bowman #305 Willie Mays Rookie Card – PSA...,15,0,https://goldin.co/item/1951-bowman-305-willie-...,"$186,000",Thu,3/16/23,0,3:30,AM
1,1958 Topps #285 Frank Robinson – PSA GEM MT 10...,5,0,https://goldin.co/item/1958-topps-285-frank-ro...,"$84,000",Thu,3/16/23,0,3:30,AM
2,1951 Bowman #253 Mickey Mantle Rookie Card - P...,13,0,https://goldin.co/item/1951-bowman-253-mickey-...,"$74,400",Thu,5/18/23,0,4:30,AM
3,1952 Topps #311 Mickey Mantle - PSA VG 3,20,0,https://goldin.co/item/1952-topps-311-mickey-m...,"$50,402",Thu,5/18/23,0,4:30,AM
4,1967 Topps #581 Tom Seaver Rookie Card - SGC G...,12,0,https://goldin.co/item/1967-topps-rookie-high-...,"$73,200",Thu,4/27/23,0,4:30,AM
...,...,...,...,...,...,...,...,...,...,...
11589,1996 Topps Mickey Mantle Finest #5 Mickey Mant...,4,0,https://goldin.co/item/1996-topps-mickey-mantl...,$13,Fri,4/21/23,0,4:15,AM
11590,1995 Upper Deck Minor League M.J. One On One #...,3,0,https://goldin.co/item/1995-upper-deck-minor-l...,$11,Fri,4/07/23,0,4:15,AM
11592,1996 Upper Deck Collector's Choice Crash Winne...,2,0,https://goldin.co/item/1996-collector-s-choice...,$8,Fri,4/28/23,0,4:15,AM
11593,1996 Topps Mantle Finest 1960 Topps Reprint #1...,3,0,https://goldin.co/item/1996-topps-mantle-fines...,$13,Fri,4/21/23,0,4:15,AM
11594,1995 Upper Deck Minor League M.J. One On One #...,"9789,103",1,https://goldin.co/item/1995-upper-deck-minor-l...,$6,Fri,4/07/23,0,4:00,AM

In [375]:
df = pd.read_csv("Baseball.csv")
df.drop(df.columns[0], axis=1, inplace=True)
df.to_csv("Baseball.csv")
df

,title,bids,err_bids,link,price,weekday,date,err_date,hour,ampm,Description,price_cln
0,1951 Bowman #305 Willie Mays Rookie Card – PSA...,15,0,https://goldin.co/item/1951-bowman-305-willie-...,"$186,000",Thu,3/16/2023,0,3:30,AM,No Data,186000
1,1958 Topps #285 Frank Robinson – PSA GEM MT 10...,5,0,https://goldin.co/item/1958-topps-285-frank-ro...,"$84,000",Thu,3/16/2023,0,3:30,AM,Graded GEM MT 10 by PSA (30203613). Hall of Fa...,84000
2,1951 Bowman #253 Mickey Mantle Rookie Card - P...,13,0,https://goldin.co/item/1951-bowman-253-mickey-...,"$74,400",Thu,5/18/2023,0,4:30,AM,"Graded NM 7 by PSA (01728756). Hall of Famer, ...",74400
3,1952 Topps #311 Mickey Mantle - PSA VG 3,20,0,https://goldin.co/item/1952-topps-311-mickey-m...,"$50,402",Thu,5/18/2023,0,4:30,AM,Graded VG 3 by PSA (21005962). Hall of Famer. ...,50402
4,1967 Topps #581 Tom Seaver Rookie Card - SGC G...,12,0,https://goldin.co/item/1967-topps-rookie-high-...,"$73,200",Thu,4/27/2023,0,4:30,AM,"Graded 98 GEM 10 (""GM 10"" equivalent) by SGC (...",73200
...,...,...,...,...,...,...,...,...,...,...,...,...
8388,1964 Topps #150 Willie Mays - PSA VG-EX 4,22,0,https://goldin.co/item/1964-topps-150-willie-m...,$121,Fri,3/10/2023,0,4:15,AM,"Former New York/San Francisco Giants, New York...",121
8389,1996 Topps Mickey Mantle Finest #5 Mickey Mant...,4,0,https://goldin.co/item/1996-topps-mickey-mantl...,$13,Fri,4/21/2023,0,4:15,AM,Mickey Mantle has stood among the most importa...,13
8390,1995 Upper Deck Minor League M.J. One On One #...,3,0,https://goldin.co/item/1995-upper-deck-minor-l...,$11,Fri,4/7/2023,0,4:15,AM,No Data,11
8391,1996 Upper Deck Collector's Choice Crash Winne...,2,0,https://goldin.co/item/1996-collector-s-choice...,$8,Fri,4/28/2023,0,4:15,AM,No Data,8
8392,1996 Topps Mantle Finest 1960 Topps Reprint #1...,3,0,https://goldin.co/item/1996-topps-mantle-fines...,$13,Fri,4/21/2023,0,4:15,AM,No Data,13

In [260]:
long = len(df)
for i in range(0,long):
    try:
        if((df.iloc[i, 2]==1) or (df.iloc[i,7]==1)):
            df.drop(index=i,inplace=True)
    except:
        print("ERR ", i)
df

,title,bids,err_bids,link,price,weekday,date,err_date,hour,ampm
0,1951 Bowman #305 Willie Mays Rookie Card – PSA...,15,0,https://goldin.co/item/1951-bowman-305-willie-...,"$186,000",Thu,3/16/2023,0,3:30,AM
1,1958 Topps #285 Frank Robinson – PSA GEM MT 10...,5,0,https://goldin.co/item/1958-topps-285-frank-ro...,"$84,000",Thu,3/16/2023,0,3:30,AM
2,1951 Bowman #253 Mickey Mantle Rookie Card - P...,13,0,https://goldin.co/item/1951-bowman-253-mickey-...,"$74,400",Thu,5/18/2023,0,4:30,AM
3,1952 Topps #311 Mickey Mantle - PSA VG 3,20,0,https://goldin.co/item/1952-topps-311-mickey-m...,"$50,402",Thu,5/18/2023,0,4:30,AM
4,1967 Topps #581 Tom Seaver Rookie Card - SGC G...,12,0,https://goldin.co/item/1967-topps-rookie-high-...,"$73,200",Thu,4/27/2023,0,4:30,AM
...,...,...,...,...,...,...,...,...,...,...
8388,1964 Topps #150 Willie Mays - PSA VG-EX 4,22,0,https://goldin.co/item/1964-topps-150-willie-m...,$121,Fri,3/10/2023,0,4:15,AM
8389,1996 Topps Mickey Mantle Finest #5 Mickey Mant...,4,0,https://goldin.co/item/1996-topps-mickey-mantl...,$13,Fri,4/21/2023,0,4:15,AM
8390,1995 Upper Deck Minor League M.J. One On One #...,3,0,https://goldin.co/item/1995-upper-deck-minor-l...,$11,Fri,4/7/2023,0,4:15,AM
8391,1996 Upper Deck Collector's Choice Crash Winne...,2,0,https://goldin.co/item/1996-collector-s-choice...,$8,Fri,4/28/2023,0,4:15,AM
8392,1996 Topps Mantle Finest 1960 Topps Reprint #1...,3,0,https://goldin.co/item/1996-topps-mantle-fines...,$13,Fri,4/21/2023,0,4:15,AM

In [262]:
df.to_csv("Baseball1.csv")

In [372]:
#df["Description"] = ''

<a id='save'>Save into CSV file</a>

In [370]:
start = 0
end = 8393
index =10
df.to_csv('Baseball1.csv')
df.iloc[start:end,:]

,title,bids,err_bids,link,price,weekday,date,err_date,hour,ampm,Description,price_cln
0,1951 Bowman #305 Willie Mays Rookie Card – PSA...,15,0,https://goldin.co/item/1951-bowman-305-willie-...,"$186,000",Thu,3/16/2023,0,3:30,AM,No Data,186000
1,1958 Topps #285 Frank Robinson – PSA GEM MT 10...,5,0,https://goldin.co/item/1958-topps-285-frank-ro...,"$84,000",Thu,3/16/2023,0,3:30,AM,Graded GEM MT 10 by PSA (30203613). Hall of Fa...,84000
2,1951 Bowman #253 Mickey Mantle Rookie Card - P...,13,0,https://goldin.co/item/1951-bowman-253-mickey-...,"$74,400",Thu,5/18/2023,0,4:30,AM,"Graded NM 7 by PSA (01728756). Hall of Famer, ...",74400
3,1952 Topps #311 Mickey Mantle - PSA VG 3,20,0,https://goldin.co/item/1952-topps-311-mickey-m...,"$50,402",Thu,5/18/2023,0,4:30,AM,Graded VG 3 by PSA (21005962). Hall of Famer. ...,50402
4,1967 Topps #581 Tom Seaver Rookie Card - SGC G...,12,0,https://goldin.co/item/1967-topps-rookie-high-...,"$73,200",Thu,4/27/2023,0,4:30,AM,"Graded 98 GEM 10 (""GM 10"" equivalent) by SGC (...",73200
...,...,...,...,...,...,...,...,...,...,...,...,...
8388,1964 Topps #150 Willie Mays - PSA VG-EX 4,22,0,https://goldin.co/item/1964-topps-150-willie-m...,$121,Fri,3/10/2023,0,4:15,AM,"Former New York/San Francisco Giants, New York...",121
8389,1996 Topps Mickey Mantle Finest #5 Mickey Mant...,4,0,https://goldin.co/item/1996-topps-mickey-mantl...,$13,Fri,4/21/2023,0,4:15,AM,Mickey Mantle has stood among the most importa...,13
8390,1995 Upper Deck Minor League M.J. One On One #...,3,0,https://goldin.co/item/1995-upper-deck-minor-l...,$11,Fri,4/7/2023,0,4:15,AM,No Data,11
8391,1996 Upper Deck Collector's Choice Crash Winne...,2,0,https://goldin.co/item/1996-collector-s-choice...,$8,Fri,4/28/2023,0,4:15,AM,No Data,8
8392,1996 Topps Mantle Finest 1960 Topps Reprint #1...,3,0,https://goldin.co/item/1996-topps-mantle-fines...,$13,Fri,4/21/2023,0,4:15,AM,No Data,13

In [371]:
long = len(df)
driver =webdriver.Chrome()
for i in range(start,end):
    if(pd.isnull(df.iloc[i,index]) or df.iloc[i,index]=='NaN' or df.iloc[i,index]==""):
        print(i ," in ", long)
        flag = 1
        try:
            link = df.at[i,"link"]
        except:
            print("Error in ", i)
            flag = 0
        if(flag):
            driver.get(link)
            driver.implicitly_wait(8)
        try:
            des = driver.find_element(By.XPATH,"//div[@class='css-175oi2r'][@id = 'html-description']").text
        except:
            des = 'No Data'
        df.iloc[i,index]=des
print("END")

END

    For saveing df into CSV file, I need to do again [here](#save)